### ISSUE TITLE
Issue with dependency "node-fetch": "cjs"

### ISSUE THREAD

**Issue by agracio** [DesignLiquido/xslt-processor#104]
Hi,
There is a new deprecation warning that is coming from dependency "node-fetch": "cjs" . It has a dependency on old version of `whatwg-url` module that is now throwing deprecation error in Node.js.

```
(node:451448) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```

Nide.js 22.7.0

**Comment by agracio** [comment]
@leonelsanchesdasilva 
Only got around to testing now, unfortunately still the same problem with "node-fetch": "release-2.x", it references "whatwg-url": "^5.0.0" that has the issue and throws a red deprecation warning into the console every time 'xslt-processor' its invoked.

**Comment by leonelsanchesdasilva** [comment]
@agracio I released another version today, this time forcing `whatwg-url` to version 14. I believe this should resolve the issue now. https://github.com/DesignLiquido/xslt-processor/releases/tag/v3.2.3

**Comment by agracio** [comment]
Still same issue, maybe package.json overrides do not apply when `xslt-processor` is installed as dependency in another project. I will try to add similar overrides in my project maybe it will help.

**Comment by agracio** [comment]
@leonelsanchesdasilva Any ideas how to tackle this problem?

**Comment by leonelsanchesdasilva** [comment]
> @leonelsanchesdasilva Any ideas how to tackle this problem?

I'm considering replacing `node-fetch` by `axios`. The problem will be the package bloating. 

Another alternative is to update `node-fetch` to the most recent version, but I think I had problems I tried to package it. I'll have to test it properly.

**Comment by agracio** [comment]
Thanks, let me know if I can be of any help.
Started using it recently for a project but having a red deprecation message would be an issue for an end user.

**Comment by leonelsanchesdasilva** [comment]
@agracio From initial tests using [the traditional `fetch()` from Node.js 18](https://nodejs.org/dist/v18.20.4/docs/api/globals.html#fetch), I think I can simply get rid of node-fetch. I use node-fetch because of `<xsl:include>` and `<xsl:import>`, but if people use Node.js below version 17.5.0, I'll have to test the Node.js version to inform that `<xsl:include>` and `<xsl:import>` are not supported.

**Comment by leonelsanchesdasilva** [comment]
@agracio Please test version https://github.com/DesignLiquido/xslt-processor/releases/tag/v3.3.0. I removed node-fetch completely.

**Comment by agracio** [comment]
I think something went wrong with NPM publishing, 3.3.0 still shows dependency on 'node-fetch' in NPM although it is removed in GitHub repo. Generated JS code also requires 'node-fetch'.

**Comment by agracio** [comment]
Perfect works like a charm now. Tanks!
