### ISSUE TITLE
xsl:text with disable-output-escaping

### ISSUE THREAD

**Issue by AndreyMiloserdov** [DesignLiquido/xslt-processor#111]
```xml
<xsl:text disable-output-escaping='yes'>&lt;!DOCTYPE html&gt;</xsl:text>
```
should insert 
```html
<!DOCTYPE html>
```
to the output file
(https://stackoverflow.com/questions/3387127/set-html5-doctype-with-xslt)

**Comment by leonelsanchesdasilva** [comment]
Resolved by https://github.com/DesignLiquido/xslt-processor/releases/tag/v3.2.2.
