### ISSUE TITLE
Missing generate-id function

### ISSUE THREAD

**Issue by TheKnarf** [DesignLiquido/xslt-processor#24]
> The `generate-id` function generates a unique id for the first node in a given node-set and returns a string containing that id. This function is an XSLT-specific addition to XPath. It is not a part of the core XPath function library. - MDN

- [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/generate-id)

- [StackOverflow exampe](https://unix.stackexchange.com/questions/394162/insert-a-tag-with-a-unique-identifier-into-a-xml)

**Comment by berenddeboer** [comment]
See #37, at least you get a better error message.
