### ISSUE TITLE
import and include

### ISSUE THREAD

**Issue by Nabrok** [DesignLiquido/xslt-processor#27]
Is any work currently being done to support include and import?

**Comment by johanneswilm** [comment]
Hey, no unless you guys do it, no-one else is.

**Comment by Caesar2011** [comment]
I got it to work importing the following

`import {xmlParse, xsltProcess} from '/node_modules/xslt-processor/src/index.js';`

**Comment by leonelsanchesdasilva** [comment]
This was resolved at https://github.com/DesignLiquido/xslt-processor/releases/tag/v1.0.0
