### ISSUE TITLE
local-name()

### ISSUE THREAD

**Issue by JonathanRowell** [DesignLiquido/xslt-processor#32]
One could do with local-name(), useful when dynamically creating elements and it should be simple to implement as it follows on from 'name'.
``
'local-name' (ctx) {
        assert(this.args.length == 1 || this.args.length == 0);
        let n;
        if (this.args.length == 0) {
            n = [ctx.node];
        } else {
            n = this.args[0].evaluate(ctx).nodeSetValue();
        }

        if (n.length == 0) {
            return new StringValue('');
        } else {
            let name = n[0].nodeName;
            if(name.contains':') {
            	return new StringValue(name.slice(name.indexOf(':')+1));
            } else {
            	return new StringValue(name);
            }
        }
    },
`

**Comment by JonathanRowell** [comment]
Sorry I got the code insert wrong!

**Comment by berenddeboer** [comment]
Ah, missed this, I just implemented this in #36.

But in general this package doesn't handle namespaces.

**Comment by josiahwitheford** [comment]
Hey there, is there any chance this feature is going to be released soon?

**Comment by leonelsanchesdasilva** [comment]
Hi @josiahwitheford. This was released on https://github.com/DesignLiquido/xslt-processor/releases/tag/v1.0.0. Please let me know if any adjustments are required.

**Comment by leonelsanchesdasilva** [comment]
For now I'm closing this, but should return in the future if any problems arise from this implementation.
