### ISSUE TITLE
Upper and Lower case

### ISSUE THREAD

**Issue by JonathanRowell** [DesignLiquido/xslt-processor#33]
XSLT 1.0 has a MAJOR flaw in that it has no upper/lower case conversion without resorting to "translate", which only solves half the problem.

XSLT 2.0 has native functions just like Javascript which solve the whole problem.

These two functions ought to be simple to implement. Could you add them please?

**Comment by leonelsanchesdasilva** [comment]
Hi @JonathanRowell. Can you please provide usage examples of what you imagine it should be the behavior?

**Comment by JonathanRowell** [comment]
The best reference for the behavior of upper-case() is given in the O'Reilly book XSLT 2.0 (https://www.oreilly.com/library/view/xslt-2nd-edition/9780596527211/re176.html). It is also contained in the XQuery standard see Priscilla Walmsley 'sbook (again O'Reilly) page 627. I use it in comparison cases of bibliographic data to find out whether Antonin Dvorak is in fact Ántonin  Dvořák. The same with Greek, Russian and a host of other names. Convert to upper case (difficult without using complete Unicode) and then throw away the accents (easy with translate).
