### ISSUE TITLE
Status of this project: only handles trivial cases it seems

### ISSUE THREAD

**Issue by berenddeboer** [DesignLiquido/xslt-processor#40]
So far every template I've tried has failed. I have 2 decades of experience with XSLT and I think 99% of my templates would not be handled properly by this library. But there's no warning anywhere about the status of this project, and the TODO list is basically empty. See for example #39: that's a major issue.

I can go on and on, but I think this project should demonstrate it can run much more of the XSLT spec before it is ready for production use.

It's a shame, as this is the only attempt at a nodejs native implementation I've found.

Anyway, I think the project should put up some huge warning signs to save people time as probably nothing they'll try will work.

**Comment by drekbour** [comment]
Seconded. It should make very clear this is a WIP and doesn't yet support XSLT 1.0

**Comment by leonelsanchesdasilva** [comment]
This project is back to life. We should have more versions in the next weeks. 

I'm closing this since it's not a real issue.
