### ISSUE TITLE
Lack of error messages

### ISSUE THREAD

**Issue by mjml** [DesignLiquido/xslt-processor#45]
Possibly the most infuriating thing is that there are no error messages. If it doesn't like your stylesheet, it just fails silently and produces an empty output. Not nice! XSLT can get quite complicated -- it would be preferable if there was a message or maybe a line number and column number to show you where it balked.

**Comment by leonelsanchesdasilva** [comment]
Hi @mjml. We are implementing a series of validations in the library, starting by https://github.com/DesignLiquido/xslt-processor/pull/69. If you still face scenarios that deserve to throw errors in the future, please open another issue with more specific details. Thanks for your contribution!
