### ISSUE TITLE
Is there a way to provide arguments?

### ISSUE THREAD

**Issue by coder-mike** [DesignLiquido/xslt-processor#46]
The .NET equivalent [XSLT transformer](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xsl.xslcompiledtransform.transform?view=net-5.0#System_Xml_Xsl_XslCompiledTransform_Transform_System_Xml_XmlReader_System_Xml_Xsl_XsltArgumentList_System_IO_TextWriter_) allows you to provide arguments to satisfy `<xsl:param name="...">` in the XSLT doc.

```cs
public void Transform(System.Xml.XmlReader input, System.Xml.Xsl.XsltArgumentList? arguments, System.IO.TextWriter results);
```

I'm wondering if there's any equivalent with xslt-processor or a work-around?

**Comment by ForbiddenEra** [comment]
I also want to know?

You, could, in theory, force them into your xml before processing..but shouldn't have to
