### ISSUE TITLE
Multiple match

### ISSUE THREAD

**Issue by marcobalestra** [DesignLiquido/xslt-processor#49]
In case of multiple node matches, instead of applying to the closest match all of the matches are applied at the same time.

e.g:

```
	<xsl:template match="*">
		<node name="{name(.)" />
		<xsl:apply-templates select="@*" />
		<xsl:apply-templates select="*" />
	</xsl:template>

	<xsl:template match="creationTime" />

	<xsl:template match="/*/submissionTime">
		<foo>bar</foo>
		<xsl:apply-templates select="*" />
	</xsl:template>
```

In this case

- ```<node name="creationTime" />``` is created
- creationTime descendant nodes are considered
- ```<node name="submissionTime" />``` is created
- submissionTime descendant nodes are considered twice

I also tried by assigning priority to template matches, but it didn't solve the issue.

**Comment by leonelsanchesdasilva** [comment]
Hi @marcobalestra. Can you please share with the a sample XML?

**Comment by marcobalestra** [comment]
Of course…

consider this XML:

```html
<root>
    <typeA />  
    <typeB />  
</root>
``` 


and this XSLT:

```html
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	
	<xsl:output method="xml" version="1.0" encoding="utf-8" indent="yes" />

	<xsl:template match="*|/*">
		<outputUnknown original-name="{name(.)}">
			<xsl:apply-templates select="*" />
		</outputUnknown>
	</xsl:template>

	<xsl:template match="typeA">
		<outputA />
	</xsl:template>

	<xsl:template match="/*/typeB">
		<outputB>I have text!</outputB>
	</xsl:template>

</xsl:stylesheet>
```

Expected output:

```html
<outputUnknown original-name="root">
	<outputA />
	<outputB>I have text!</outputB>
</typeUnknown>
```

Actual output:

```html
<outputUnknown original-name="root">
	<outputA original-name="typeA"/>
	<outputB original-name="typeB"></outputB>
</typeUnknown>
```

You can see that in both cases (typeA and typeB) the result is actually a mix of the first template and the one (2nd or 3rd) that is expected to be **the only** to match.

**_In addition…_**

Furthermore, and this seems to be another bug, if the first template only matches `<xsl:template match="*">` (that is expected to match `/*` as well) the output is expected to be the same initially expected, while it changes again:

```html
<outputB></outputB>
```

I'm a big fan of XSLT, ready and willing to support.  
All tests were performed using [the static example provided](https://github.com/DesignLiquido/xslt-processor/blob/main/interactive-tests/xslt.html).

**Comment by leonelsanchesdasilva** [comment]
@marcobalestra Thanks, this helps me enormously. 

I should work on these bugs now. Will let you know when this is ready. 

Happy to have your support!

**Comment by leonelsanchesdasilva** [comment]
@marcobalestra This problem is now solved acoordingly at https://github.com/DesignLiquido/xslt-processor/releases/tag/v1.2.0.
