### ISSUE TITLE
xsl:number not implemented

### ISSUE THREAD

**Issue by Marvbudd** [DesignLiquido/xslt-processor#51]
I apologize if this is rough. I'm a newby at node.js and using this processor. I'm trying to reimplement a project that I had working back in Win98 days.

Using a simple test app to do a transform I'm getting an error:
======================
mbudd@TreeClimberLap:~/Documents/electron/xslt$ node --trace-uncaught index.js 
Debugger attached.

node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^
Waiting for the debugger to disconnect...
not implemented: number
Thrown at:
    at loadESM (node:internal/process/esm_loader:94:31)

Node.js v17.3.0
=====================
I have isolated it down to one line in my .xslt file:
          <xsl:number count="item" />

Is this something that is already known, or would a minimum example case be helpful? Is there a workaround?

**Comment by Marvbudd** [comment]
I replaced the offending line with 
          <xsl:value-of select="count(item)" />
and my problems went away. Looks like I was using an old construct.

Please ignore/delete/obliterate/solve this issue.

**Comment by leonelsanchesdasilva** [comment]
Closed as requested.
