### ISSUE TITLE
Implement <xsl:include>

### ISSUE THREAD

**Issue by inqb** [DesignLiquido/xslt-processor#71]

**Comment by rafaelcor** [comment]
Hi, I wanted to ask if this was implemented or is still WIP?
Thanks

**Comment by leonelsanchesdasilva** [comment]
Hi @rafaelcor. Yes, I'll let you know when it is ready.

**Comment by leonelsanchesdasilva** [comment]
Some thoughts here:

`<xsl:include>` uses `href` as a single parameter. It means that it's a net access (HTTP, in general). To make it work for JS in browser, we need to use [the fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). 

Node, in turn, has a package called [`node-fetch`](https://www.npmjs.com/package/node-fetch). For this to work, first we need to detect whether there's a `window.fetch` object defined in the environment. If not, we try to `require()` `node-fetch`.

**Comment by leonelsanchesdasilva** [comment]
I started an implementation here: https://github.com/DesignLiquido/xslt-processor/tree/xsl-include. 

This modification will have a major impact in this lib.
